//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Pagos_Eventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int idPDF { get; set; }
        public Nullable<System.Guid> idComprobante { get; set; }
        public byte[] pdf { get; set; }
        public string nombre { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
    }
}
