//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Pagos_Eventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Comprobantes = new HashSet<Comprobantes>();
        }
    
        public System.Guid idUsuario { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<Comprobantes> Comprobantes { get; set; }
    }
}
